
# - name: Go to the docker compose folder and execute command
#   command: chdir="{{ docker_compose_folder }}"

- name: build the docker-compose
  command: chdir="{{ docker_compose_folder }}" docker-compose build
  when: 
    - run_service

- name: up the docker compose
  command: chdir="{{ docker_compose_folder }}" docker-compose up -d 
  when: 
    - run_service


  #docker build -t abdul-bp/alpine-nginx:1.2 .
  #docker rm -f $(docker ps -a -q)
  #docker run -d -p 8081:80 abdul-bp/alpine-nginx:1.2
